# Generated by Django 3.2.7 on 2021-09-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesuarusitem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'thesaurus_thesuarusitem',
                'managed': True,
            },
        ),
    ]
